name: Generate snake animation

on:
  schedule: # Ejecutar cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main  # Cambiado de "master" a "main", usa el que tengas

jobs:
  generate:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Generar snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Crear branch `output` si no existe
        run: |
          git fetch origin
          if ! git rev-parse --verify origin/output; then
            git branch output
            git push origin output
          fi

      - name: Subir snake.svg al branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Actualizando snake.svg 🐍"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
